# Generated by Django 5.0.1 on 2024-02-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_tag_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
