# Generated by Django 5.0.1 on 2024-02-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_delete_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
